version: '3'

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/certs:/etc/nginx/certs:ro
      - /mnt/confd:/etc/nginx/conf.d
      - /mnt/vhostd:/etc/nginx/vhost.d
      - /mnt/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: duch/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - /mnt/certs:/etc/nginx/certs:rw
      - /mnt/confd:/etc/nginx/conf.d
      - /mnt/vhostd:/etc/nginx/vhost.d
      - /mnt/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-web:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /mnt/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pitelework.duckdns.org
      - LETSENCRYPT_HOST=pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com

  php-apache:
    image: php:7.2.1-apache
    ports:
      - 8050:80
    volumes:
      - /mnt/www/docker-study.loc/recipe-03/php:/var/www/html:z
    links:
      - 'mariadb'
    environment:
      - VIRTUAL_HOST=ch.pitelework.duckdns.org
      - LETSENCRYPT_HOST=ch.pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com

  mariadb:
    image: mariadb:10.1
    volumes:
      - /mnt/mariadb/data:/var/lib/mysql
    environment:
      TZ: "Europe/Madrid"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "Ew4UgwxmPz0lI1EsXcdrYT0scQ"
      MYSQL_USER: 'pitelework'
      MYSQL_PASSWORD: 'tEw4UgwxmPz0lI1EsXcdrYT0scQ'
      MYSQL_DATABASE: 'control_asistencia'
    ports:
      - 3306:3306

  adminer:
    image: adminer
    container_name: bi_adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      - VIRTUAL_HOST=adminer.pitelework.duckdns.org
      - LETSENCRYPT_HOST=adminer.pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com

  db:
    image: postgres
    restart: always
    volumes:
      - /mnt/postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - /mnt/nextcloud/data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - VIRTUAL_HOST=cloud.pitelework.duckdns.org
      - LETSENCRYPT_HOST=cloud.pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

secrets:
  nextcloud_admin_password:
    file: /mnt/nextcloud/secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: /mnt/nextcloud/secrets/nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: /mnt/nextcloud/secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: /mnt/nextcloud/secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: /mnt/nextcloud/secrets/postgres_user.txt # put postgresql username to this file