version: '3'

services:
  nginx-proxy:
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/certs:/etc/nginx/certs:ro
      - /mnt/confd:/etc/nginx/conf.d
      - /mnt/vhostd:/etc/nginx/vhost.d
      - /mnt/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: duch/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - /mnt/certs:/etc/nginx/certs:rw
      - /mnt/confd:/etc/nginx/conf.d
      - /mnt/vhostd:/etc/nginx/vhost.d
      - /mnt/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx_fredrikson:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /mnt/www:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=pitelework.duckdns.org
      - LETSENCRYPT_HOST=pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com
      
  db:
    image: postgres
    restart: always
    volumes:
      - /mnt/postgres/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - 5432:5432
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
  
  adminer:
    image: adminer
    container_name: bi_adminer
    restart: always
    ports:
      - 8090:8080
    environment:
      - VIRTUAL_HOST=adminer.pitelework.duckdns.org
      - LETSENCRYPT_HOST=adminer.pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - /mnt/nextcloud/data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - VIRTUAL_HOST=cloud.pitelework.duckdns.org
      - LETSENCRYPT_HOST=cloud.pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

  bitwarden:
    image: bitwardenrs/server:latest 
    expose:
      - "90"
    volumes:
      - /mnt/bitwarden:/data
    restart: on-failure
    environment:
      - VIRTUAL_HOST=bitwarden.pitelework.duckdns.org
      - LETSENCRYPT_HOST=bitwarden.pitelework.duckdns.org
      - LETSENCRYPT_EMAIL=jorgealonsodev@gmail.com

secrets:
  nextcloud_admin_password:
    file: /mnt/nextcloud/secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: /mnt/nextcloud/secrets/nextcloud_admin_user.txt # put admin username to this file
  postgres_db:
    file: /mnt/nextcloud/secrets/postgres_db.txt # put postgresql db name to this file
  postgres_password:
    file: /mnt/nextcloud/secrets/postgres_password.txt # put postgresql password to this file
  postgres_user:
    file: /mnt/nextcloud/secrets/postgres_user.txt # put postgresql username to this file